services:
    db:
        image: postgres:17
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}

    backend:
        image: registry.nassimlounadi.fr/nassimlounadi/matchroom-backend
        depends_on:
            - db

    frontend:
        image: registry.nassimlounadi.fr/nassimlounadi/matchroom-frontend

    nginx:
        image: registry.nassimlounadi.fr/nassimlounadi/matchroom-nginx
        ports:
            - "4010:80"
        depends_on:
            - backend
            - frontend
